"""Reusable UI components for the EOIP Streamlit application."""

from eoip.app.components.charts import (
    apply_eoip_chart_style,
    eoip_actual_expected_colors,
    eoip_forecast_style,
    plotly_chart_config,
    render_plotly_chart,
    style_eoip_donut,
)
from eoip.app.components.common import (
    PageContext,
    StatusLevel,
    dashboard_loading,
    load_dashboard_data,
    render_dataframe,
    render_divider,
    render_empty_state,
    render_page_context,
    render_page_intro,
    render_section_header,
    render_status,
)
from eoip.app.components.downloads import (
    build_report_filename,
    dataframe_to_csv_bytes,
    render_csv_download,
)
from eoip.app.components.filters import (
    DEFAULT_EQUIPMENT,
    DEFAULT_PLANTS,
    FilterSelection,
    format_filter_caption,
    get_filter_selection,
    initialize_filter_state,
    normalize_filter_selection,
    page_context_from_filters,
    render_filter_context,
    render_global_filters,
    set_filter_selection,
)
from eoip.app.components.kpi import MetricCard, render_metric_card, render_metric_row

__all__ = [
    "DEFAULT_EQUIPMENT",
    "DEFAULT_PLANTS",
    "FilterSelection",
    "MetricCard",
    "PageContext",
    "StatusLevel",
    "apply_eoip_chart_style",
    "build_report_filename",
    "dataframe_to_csv_bytes",
    "dashboard_loading",
    "eoip_actual_expected_colors",
    "eoip_forecast_style",
    "format_filter_caption",
    "get_filter_selection",
    "initialize_filter_state",
    "load_dashboard_data",
    "normalize_filter_selection",
    "page_context_from_filters",
    "plotly_chart_config",
    "render_csv_download",
    "render_dataframe",
    "render_divider",
    "render_empty_state",
    "render_filter_context",
    "render_global_filters",
    "render_metric_card",
    "render_metric_row",
    "render_page_intro",
    "render_page_context",
    "render_plotly_chart",
    "style_eoip_donut",
    "render_section_header",
    "render_status",
    "set_filter_selection",
]
