# ruff: noqa: E501

"""initial EOIP schema

Revision ID: a1c9cbd16e30
Revises:
Create Date: 2026-08-13 12:20:36.869320

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1c9cbd16e30"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plants",
        sa.Column("plant_id", sa.String(length=9), nullable=False),
        sa.Column("plant_name", sa.String(length=150), nullable=False),
        sa.Column("region", sa.String(length=100), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("dc_capacity_mw", sa.Float(), nullable=False),
        sa.Column("ac_capacity_mw", sa.Float(), nullable=False),
        sa.Column("commissioning_date", sa.Date(), nullable=False),
        sa.Column(
            "status", sa.String(length=30), server_default="operational", nullable=False
        ),
        sa.Column(
            "timezone_name", sa.String(length=100), server_default="UTC", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('operational', 'planned_outage', 'decommissioned')",
            name=op.f("ck_plants_valid_status"),
        ),
        sa.CheckConstraint(
            "ac_capacity_mw <= dc_capacity_mw",
            name=op.f("ck_plants_ac_not_greater_than_dc"),
        ),
        sa.CheckConstraint(
            "ac_capacity_mw > 0", name=op.f("ck_plants_ac_capacity_positive")
        ),
        sa.CheckConstraint(
            "dc_capacity_mw > 0", name=op.f("ck_plants_dc_capacity_positive")
        ),
        sa.CheckConstraint(
            "latitude >= -90.0 AND latitude <= 90.0",
            name=op.f("ck_plants_latitude_range"),
        ),
        sa.CheckConstraint(
            "longitude >= -180.0 AND longitude <= 180.0",
            name=op.f("ck_plants_longitude_range"),
        ),
        sa.PrimaryKeyConstraint("plant_id", name=op.f("pk_plants")),
    )
    op.create_index(
        "ix_plants_commissioning_date", "plants", ["commissioning_date"], unique=False
    )
    op.create_index("ix_plants_region", "plants", ["region"], unique=False)
    op.create_index("ix_plants_status", "plants", ["status"], unique=False)
    op.create_table(
        "budgets",
        sa.Column("budget_id", sa.String(length=9), nullable=False),
        sa.Column("plant_id", sa.String(length=9), nullable=False),
        sa.Column("budget_name", sa.String(length=150), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("allocated_amount", sa.Float(), nullable=False),
        sa.Column("spent_amount", sa.Float(), server_default="0", nullable=False),
        sa.Column(
            "currency_code", sa.String(length=3), server_default="PKR", nullable=False
        ),
        sa.Column("approved_on", sa.Date(), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default="draft", nullable=False
        ),
        sa.Column(
            "inserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('operations', 'maintenance', 'capex', 'opex', 'other')",
            name=op.f("ck_budgets_valid_category"),
        ),
        sa.CheckConstraint(
            "status <> 'approved' OR approved_on IS NOT NULL",
            name=op.f("ck_budgets_approved_status_requires_date"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'approved', 'closed')",
            name=op.f("ck_budgets_valid_status"),
        ),
        sa.CheckConstraint(
            "allocated_amount >= 0",
            name=op.f("ck_budgets_allocated_amount_non_negative"),
        ),
        sa.CheckConstraint(
            "fiscal_year >= 2000 AND fiscal_year <= 2100",
            name=op.f("ck_budgets_fiscal_year_range"),
        ),
        sa.CheckConstraint(
            "spent_amount <= allocated_amount",
            name=op.f("ck_budgets_spent_not_above_allocated"),
        ),
        sa.CheckConstraint(
            "spent_amount >= 0", name=op.f("ck_budgets_spent_amount_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.plant_id"],
            name=op.f("fk_budgets_plant_id_plants"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("budget_id", name=op.f("pk_budgets")),
    )
    op.create_index("ix_budgets_approved_on", "budgets", ["approved_on"], unique=False)
    op.create_index("ix_budgets_category", "budgets", ["category"], unique=False)
    op.create_index("ix_budgets_fiscal_year", "budgets", ["fiscal_year"], unique=False)
    op.create_index(
        "ix_budgets_plant_fiscal_year",
        "budgets",
        ["plant_id", "fiscal_year"],
        unique=False,
    )
    op.create_index("ix_budgets_plant_id", "budgets", ["plant_id"], unique=False)
    op.create_index("ix_budgets_status", "budgets", ["status"], unique=False)
    op.create_table(
        "equipment",
        sa.Column("equipment_id", sa.String(length=9), nullable=False),
        sa.Column("plant_id", sa.String(length=9), nullable=False),
        sa.Column("equipment_name", sa.String(length=150), nullable=False),
        sa.Column("equipment_type", sa.String(length=40), nullable=False),
        sa.Column("manufacturer", sa.String(length=100), nullable=False),
        sa.Column("model_number", sa.String(length=100), nullable=False),
        sa.Column("serial_number", sa.String(length=100), nullable=False),
        sa.Column("commissioning_date", sa.Date(), nullable=False),
        sa.Column("rated_power_kw", sa.Float(), nullable=True),
        sa.Column("parent_equipment_id", sa.String(length=9), nullable=True),
        sa.Column(
            "status", sa.String(length=30), server_default="operational", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "equipment_type IN ('string_inverter', 'central_inverter', 'transformer', 'feeder', 'weather_station', 'revenue_meter', 'protection_relay')",
            name=op.f("ck_equipment_valid_equipment_type"),
        ),
        sa.CheckConstraint(
            "status IN ('operational', 'planned_outage', 'forced_outage', 'maintenance', 'decommissioned')",
            name=op.f("ck_equipment_valid_status"),
        ),
        sa.CheckConstraint(
            "parent_equipment_id IS NULL OR parent_equipment_id <> equipment_id",
            name=op.f("ck_equipment_not_own_parent"),
        ),
        sa.CheckConstraint(
            "rated_power_kw IS NULL OR rated_power_kw > 0",
            name=op.f("ck_equipment_rated_power_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_equipment_id"],
            ["equipment.equipment_id"],
            name=op.f("fk_equipment_parent_equipment_id_equipment"),
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.plant_id"],
            name=op.f("fk_equipment_plant_id_plants"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("equipment_id", name=op.f("pk_equipment")),
        sa.UniqueConstraint("serial_number", name="uq_equipment_serial_number"),
    )
    op.create_index(
        "ix_equipment_commissioning_date",
        "equipment",
        ["commissioning_date"],
        unique=False,
    )
    op.create_index(
        "ix_equipment_equipment_type", "equipment", ["equipment_type"], unique=False
    )
    op.create_index(
        "ix_equipment_parent_equipment_id",
        "equipment",
        ["parent_equipment_id"],
        unique=False,
    )
    op.create_index("ix_equipment_plant_id", "equipment", ["plant_id"], unique=False)
    op.create_index("ix_equipment_status", "equipment", ["status"], unique=False)
    op.create_table(
        "tariffs",
        sa.Column("tariff_id", sa.String(length=9), nullable=False),
        sa.Column("plant_id", sa.String(length=9), nullable=False),
        sa.Column("tariff_name", sa.String(length=150), nullable=False),
        sa.Column("tariff_type", sa.String(length=40), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("energy_rate_per_kwh", sa.Float(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("demand_rate_per_kw", sa.Float(), nullable=True),
        sa.Column(
            "escalation_rate_pct", sa.Float(), server_default="0", nullable=False
        ),
        sa.Column(
            "status", sa.String(length=20), server_default="active", nullable=False
        ),
        sa.Column("contract_reference", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column(
            "inserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'expired' OR effective_to IS NOT NULL",
            name=op.f("ck_tariffs_expired_status_requires_end_date"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'expired', 'cancelled')",
            name=op.f("ck_tariffs_valid_status"),
        ),
        sa.CheckConstraint(
            "tariff_type IN ('fixed', 'time_of_use', 'feed_in', 'power_purchase_agreement', 'merchant')",
            name=op.f("ck_tariffs_valid_tariff_type"),
        ),
        sa.CheckConstraint(
            "demand_rate_per_kw IS NULL OR demand_rate_per_kw >= 0",
            name=op.f("ck_tariffs_demand_rate_non_negative"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_tariffs_effective_date_order"),
        ),
        sa.CheckConstraint(
            "energy_rate_per_kwh >= 0", name=op.f("ck_tariffs_energy_rate_non_negative")
        ),
        sa.CheckConstraint(
            "escalation_rate_pct >= 0 AND escalation_rate_pct <= 100",
            name=op.f("ck_tariffs_escalation_rate_range"),
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.plant_id"],
            name=op.f("fk_tariffs_plant_id_plants"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tariff_id", name=op.f("pk_tariffs")),
    )
    op.create_index(
        "ix_tariffs_effective_from", "tariffs", ["effective_from"], unique=False
    )
    op.create_index(
        "ix_tariffs_effective_to", "tariffs", ["effective_to"], unique=False
    )
    op.create_index(
        "ix_tariffs_plant_effective_from",
        "tariffs",
        ["plant_id", "effective_from"],
        unique=False,
    )
    op.create_index("ix_tariffs_plant_id", "tariffs", ["plant_id"], unique=False)
    op.create_index(
        "ix_tariffs_plant_status", "tariffs", ["plant_id", "status"], unique=False
    )
    op.create_index("ix_tariffs_status", "tariffs", ["status"], unique=False)
    op.create_index("ix_tariffs_tariff_type", "tariffs", ["tariff_type"], unique=False)
    op.create_table(
        "weather_observations",
        sa.Column("plant_id", sa.String(length=9), nullable=False),
        sa.Column("weather_station_id", sa.String(length=6), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ghi_wm2", sa.Float(), nullable=False),
        sa.Column("dni_wm2", sa.Float(), nullable=False),
        sa.Column("dhi_wm2", sa.Float(), nullable=False),
        sa.Column("ambient_temperature_c", sa.Float(), nullable=False),
        sa.Column("module_temperature_c", sa.Float(), nullable=False),
        sa.Column("wind_speed_ms", sa.Float(), nullable=False),
        sa.Column("relative_humidity_pct", sa.Float(), nullable=False),
        sa.Column(
            "quality", sa.String(length=20), server_default="valid", nullable=False
        ),
        sa.Column(
            "inserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quality IN ('valid', 'estimated', 'missing')",
            name=op.f("ck_weather_observations_valid_quality"),
        ),
        sa.CheckConstraint(
            "ambient_temperature_c >= -40 AND ambient_temperature_c <= 70",
            name=op.f("ck_weather_observations_ambient_temperature_range"),
        ),
        sa.CheckConstraint(
            "dhi_wm2 >= 0 AND dhi_wm2 <= 1500",
            name=op.f("ck_weather_observations_dhi_range"),
        ),
        sa.CheckConstraint(
            "dni_wm2 >= 0 AND dni_wm2 <= 1500",
            name=op.f("ck_weather_observations_dni_range"),
        ),
        sa.CheckConstraint(
            "ghi_wm2 >= 0 AND ghi_wm2 <= 1500",
            name=op.f("ck_weather_observations_ghi_range"),
        ),
        sa.CheckConstraint(
            "module_temperature_c >= -40 AND module_temperature_c <= 120",
            name=op.f("ck_weather_observations_module_temperature_range"),
        ),
        sa.CheckConstraint(
            "relative_humidity_pct >= 0 AND relative_humidity_pct <= 100",
            name=op.f("ck_weather_observations_relative_humidity_range"),
        ),
        sa.CheckConstraint(
            "wind_speed_ms >= 0 AND wind_speed_ms <= 70",
            name=op.f("ck_weather_observations_wind_speed_range"),
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.plant_id"],
            name=op.f("fk_weather_observations_plant_id_plants"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "weather_station_id", "timestamp", name=op.f("pk_weather_observations")
        ),
    )
    op.create_index(
        "ix_weather_observations_plant_id",
        "weather_observations",
        ["plant_id"],
        unique=False,
    )
    op.create_index(
        "ix_weather_observations_plant_timestamp",
        "weather_observations",
        ["plant_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_weather_observations_quality_timestamp",
        "weather_observations",
        ["quality", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_weather_observations_station_timestamp",
        "weather_observations",
        ["weather_station_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_weather_observations_timestamp",
        "weather_observations",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "alarms",
        sa.Column("alarm_id", sa.String(length=11), nullable=False),
        sa.Column("plant_id", sa.String(length=9), nullable=False),
        sa.Column("equipment_id", sa.String(length=9), nullable=False),
        sa.Column("alarm_code", sa.String(length=50), nullable=False),
        sa.Column("alarm_name", sa.String(length=150), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("raised_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="active", nullable=False
        ),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column(
            "is_synthetic_ground_truth",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT (status = 'acknowledged' AND acknowledged_at IS NULL)",
            name=op.f("ck_alarms_acknowledged_has_timestamp"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'acknowledged' AND cleared_at IS NOT NULL)",
            name=op.f("ck_alarms_acknowledged_has_no_cleared_at"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'active' AND cleared_at IS NOT NULL)",
            name=op.f("ck_alarms_active_has_no_cleared_at"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'cleared' AND cleared_at IS NULL)",
            name=op.f("ck_alarms_cleared_has_timestamp"),
        ),
        sa.CheckConstraint(
            "category IN ('equipment', 'grid', 'communication', 'environmental', 'performance', 'safety')",
            name=op.f("ck_alarms_valid_category"),
        ),
        sa.CheckConstraint(
            "severity IN ('informational', 'warning', 'major', 'critical')",
            name=op.f("ck_alarms_valid_severity"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'acknowledged', 'cleared')",
            name=op.f("ck_alarms_valid_status"),
        ),
        sa.CheckConstraint(
            "acknowledged_at IS NULL OR acknowledged_at >= raised_at",
            name=op.f("ck_alarms_acknowledged_not_before_raised"),
        ),
        sa.CheckConstraint(
            "cleared_at IS NULL OR acknowledged_at IS NULL OR cleared_at >= acknowledged_at",
            name=op.f("ck_alarms_cleared_not_before_acknowledged"),
        ),
        sa.CheckConstraint(
            "cleared_at IS NULL OR cleared_at >= raised_at",
            name=op.f("ck_alarms_cleared_not_before_raised"),
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.equipment_id"],
            name=op.f("fk_alarms_equipment_id_equipment"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.plant_id"],
            name=op.f("fk_alarms_plant_id_plants"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("alarm_id", name=op.f("pk_alarms")),
    )
    op.create_index("ix_alarms_alarm_code", "alarms", ["alarm_code"], unique=False)
    op.create_index("ix_alarms_category", "alarms", ["category"], unique=False)
    op.create_index("ix_alarms_equipment_id", "alarms", ["equipment_id"], unique=False)
    op.create_index(
        "ix_alarms_plant_equipment_raised_at",
        "alarms",
        ["plant_id", "equipment_id", "raised_at"],
        unique=False,
    )
    op.create_index("ix_alarms_plant_id", "alarms", ["plant_id"], unique=False)
    op.create_index("ix_alarms_raised_at", "alarms", ["raised_at"], unique=False)
    op.create_index("ix_alarms_severity", "alarms", ["severity"], unique=False)
    op.create_index("ix_alarms_status", "alarms", ["status"], unique=False)
    op.create_table(
        "ground_truth_events",
        sa.Column("ground_truth_id", sa.String(length=11), nullable=False),
        sa.Column("plant_id", sa.String(length=9), nullable=False),
        sa.Column("equipment_id", sa.String(length=9), nullable=True),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "expected_power_loss_pct", sa.Float(), server_default="0", nullable=False
        ),
        sa.Column(
            "expected_energy_loss_kwh", sa.Float(), server_default="0", nullable=False
        ),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "inserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('equipment_failure', 'performance_degradation', 'grid_outage', 'communication_loss', 'sensor_fault', 'curtailment', 'soiling', 'maintenance')",
            name=op.f("ck_ground_truth_events_valid_event_type"),
        ),
        sa.CheckConstraint(
            "severity IN ('low', 'moderate', 'high', 'critical')",
            name=op.f("ck_ground_truth_events_valid_severity"),
        ),
        sa.CheckConstraint(
            "ended_at > started_at",
            name=op.f("ck_ground_truth_events_ended_after_started"),
        ),
        sa.CheckConstraint(
            "expected_energy_loss_kwh >= 0",
            name=op.f("ck_ground_truth_events_energy_loss_non_negative"),
        ),
        sa.CheckConstraint(
            "expected_power_loss_pct >= 0 AND expected_power_loss_pct <= 100",
            name=op.f("ck_ground_truth_events_power_loss_pct_range"),
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.equipment_id"],
            name=op.f("fk_ground_truth_events_equipment_id_equipment"),
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.plant_id"],
            name=op.f("fk_ground_truth_events_plant_id_plants"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("ground_truth_id", name=op.f("pk_ground_truth_events")),
    )
    op.create_index(
        "ix_ground_truth_events_ended_at",
        "ground_truth_events",
        ["ended_at"],
        unique=False,
    )
    op.create_index(
        "ix_ground_truth_events_equipment_id",
        "ground_truth_events",
        ["equipment_id"],
        unique=False,
    )
    op.create_index(
        "ix_ground_truth_events_equipment_started_at",
        "ground_truth_events",
        ["equipment_id", "started_at"],
        unique=False,
    )
    op.create_index(
        "ix_ground_truth_events_event_type",
        "ground_truth_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        "ix_ground_truth_events_plant_id",
        "ground_truth_events",
        ["plant_id"],
        unique=False,
    )
    op.create_index(
        "ix_ground_truth_events_plant_severity",
        "ground_truth_events",
        ["plant_id", "severity"],
        unique=False,
    )
    op.create_index(
        "ix_ground_truth_events_plant_started_at",
        "ground_truth_events",
        ["plant_id", "started_at"],
        unique=False,
    )
    op.create_index(
        "ix_ground_truth_events_severity",
        "ground_truth_events",
        ["severity"],
        unique=False,
    )
    op.create_index(
        "ix_ground_truth_events_started_at",
        "ground_truth_events",
        ["started_at"],
        unique=False,
    )
    op.create_table(
        "scada_observations",
        sa.Column("plant_id", sa.String(length=9), nullable=False),
        sa.Column("equipment_id", sa.String(length=9), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active_power_kw", sa.Float(), nullable=False),
        sa.Column("interval_energy_kwh", sa.Float(), nullable=False),
        sa.Column("dc_voltage_v", sa.Float(), nullable=False),
        sa.Column("dc_current_a", sa.Float(), nullable=False),
        sa.Column("ac_voltage_v", sa.Float(), nullable=False),
        sa.Column("ac_current_a", sa.Float(), nullable=False),
        sa.Column("frequency_hz", sa.Float(), nullable=False),
        sa.Column("power_factor", sa.Float(), nullable=False),
        sa.Column("equipment_available", sa.Boolean(), nullable=False),
        sa.Column("grid_available", sa.Boolean(), nullable=False),
        sa.Column("operating_state", sa.String(length=20), nullable=False),
        sa.Column(
            "quality", sa.String(length=20), server_default="valid", nullable=False
        ),
        sa.Column(
            "inserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "operating_state <> 'normal' OR (equipment_available AND grid_available)",
            name=op.f("ck_scada_observations_normal_state_requires_availability"),
        ),
        sa.CheckConstraint(
            "operating_state IN ('normal', 'derated', 'stopped', 'fault', 'maintenance', 'night')",
            name=op.f("ck_scada_observations_valid_operating_state"),
        ),
        sa.CheckConstraint(
            "operating_state NOT IN ('stopped', 'fault', 'maintenance', 'night') OR (active_power_kw = 0 AND interval_energy_kwh = 0)",
            name=op.f("ck_scada_observations_non_generating_state_has_no_generation"),
        ),
        sa.CheckConstraint(
            "quality IN ('valid', 'estimated', 'missing')",
            name=op.f("ck_scada_observations_valid_quality"),
        ),
        sa.CheckConstraint(
            "EXTRACT(SECOND FROM timestamp) = 0",
            name=op.f("ck_scada_observations_timestamp_zero_seconds"),
        ),
        sa.CheckConstraint(
            "MOD(EXTRACT(MINUTE FROM timestamp)::integer, 15) = 0",
            name=op.f("ck_scada_observations_timestamp_interval_aligned"),
        ),
        sa.CheckConstraint(
            "ac_current_a >= 0 AND ac_current_a <= 10000",
            name=op.f("ck_scada_observations_ac_current_range"),
        ),
        sa.CheckConstraint(
            "ac_voltage_v >= 0 AND ac_voltage_v <= 50000",
            name=op.f("ck_scada_observations_ac_voltage_range"),
        ),
        sa.CheckConstraint(
            "active_power_kw >= 0 AND active_power_kw <= 50000",
            name=op.f("ck_scada_observations_active_power_range"),
        ),
        sa.CheckConstraint(
            "dc_current_a >= 0 AND dc_current_a <= 10000",
            name=op.f("ck_scada_observations_dc_current_range"),
        ),
        sa.CheckConstraint(
            "dc_voltage_v >= 0 AND dc_voltage_v <= 2000",
            name=op.f("ck_scada_observations_dc_voltage_range"),
        ),
        sa.CheckConstraint(
            "equipment_available OR (active_power_kw = 0 AND interval_energy_kwh = 0)",
            name=op.f("ck_scada_observations_unavailable_equipment_has_no_generation"),
        ),
        sa.CheckConstraint(
            "frequency_hz >= 0 AND frequency_hz <= 70",
            name=op.f("ck_scada_observations_frequency_range"),
        ),
        sa.CheckConstraint(
            "grid_available OR (active_power_kw = 0 AND interval_energy_kwh = 0)",
            name=op.f("ck_scada_observations_unavailable_grid_has_no_generation"),
        ),
        sa.CheckConstraint(
            "interval_energy_kwh >= 0 AND interval_energy_kwh <= 12500",
            name=op.f("ck_scada_observations_interval_energy_range"),
        ),
        sa.CheckConstraint(
            "power_factor >= -1 AND power_factor <= 1",
            name=op.f("ck_scada_observations_power_factor_range"),
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.equipment_id"],
            name=op.f("fk_scada_observations_equipment_id_equipment"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.plant_id"],
            name=op.f("fk_scada_observations_plant_id_plants"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "equipment_id", "timestamp", name=op.f("pk_scada_observations")
        ),
    )
    op.create_index(
        "ix_scada_observations_equipment_timestamp",
        "scada_observations",
        ["equipment_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_scada_observations_plant_id",
        "scada_observations",
        ["plant_id"],
        unique=False,
    )
    op.create_index(
        "ix_scada_observations_plant_timestamp",
        "scada_observations",
        ["plant_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_scada_observations_quality_timestamp",
        "scada_observations",
        ["quality", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_scada_observations_state_timestamp",
        "scada_observations",
        ["operating_state", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_scada_observations_timestamp",
        "scada_observations",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "incidents",
        sa.Column("incident_id", sa.String(length=11), nullable=False),
        sa.Column("plant_id", sa.String(length=9), nullable=False),
        sa.Column("equipment_id", sa.String(length=9), nullable=False),
        sa.Column("incident_name", sa.String(length=150), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="open", nullable=False
        ),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("root_cause", sa.String(length=500), nullable=True),
        sa.Column("linked_alarm_id", sa.String(length=11), nullable=True),
        sa.Column(
            "is_synthetic_ground_truth",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT (status = 'investigating' AND detected_at IS NULL)",
            name=op.f("ck_incidents_investigating_has_detected_at"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'investigating' AND resolved_at IS NOT NULL)",
            name=op.f("ck_incidents_investigating_has_no_resolved_at"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'open' AND resolved_at IS NOT NULL)",
            name=op.f("ck_incidents_open_has_no_resolved_at"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'resolved' AND resolved_at IS NULL)",
            name=op.f("ck_incidents_resolved_has_timestamp"),
        ),
        sa.CheckConstraint(
            "category IN ('equipment_failure', 'grid_event', 'communication_failure', 'performance_degradation', 'environmental_event', 'safety_event', 'planned_maintenance')",
            name=op.f("ck_incidents_valid_category"),
        ),
        sa.CheckConstraint(
            "severity IN ('low', 'moderate', 'high', 'critical')",
            name=op.f("ck_incidents_valid_severity"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'investigating', 'resolved')",
            name=op.f("ck_incidents_valid_status"),
        ),
        sa.CheckConstraint(
            "detected_at IS NULL OR detected_at >= occurred_at",
            name=op.f("ck_incidents_detected_not_before_occurred"),
        ),
        sa.CheckConstraint(
            "resolved_at IS NULL OR detected_at IS NULL OR resolved_at >= detected_at",
            name=op.f("ck_incidents_resolved_not_before_detected"),
        ),
        sa.CheckConstraint(
            "resolved_at IS NULL OR resolved_at >= occurred_at",
            name=op.f("ck_incidents_resolved_not_before_occurred"),
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.equipment_id"],
            name=op.f("fk_incidents_equipment_id_equipment"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["linked_alarm_id"],
            ["alarms.alarm_id"],
            name=op.f("fk_incidents_linked_alarm_id_alarms"),
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.plant_id"],
            name=op.f("fk_incidents_plant_id_plants"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("incident_id", name=op.f("pk_incidents")),
    )
    op.create_index("ix_incidents_category", "incidents", ["category"], unique=False)
    op.create_index(
        "ix_incidents_equipment_id", "incidents", ["equipment_id"], unique=False
    )
    op.create_index(
        "ix_incidents_linked_alarm_id", "incidents", ["linked_alarm_id"], unique=False
    )
    op.create_index(
        "ix_incidents_occurred_at", "incidents", ["occurred_at"], unique=False
    )
    op.create_index(
        "ix_incidents_plant_equipment_occurred_at",
        "incidents",
        ["plant_id", "equipment_id", "occurred_at"],
        unique=False,
    )
    op.create_index("ix_incidents_plant_id", "incidents", ["plant_id"], unique=False)
    op.create_index("ix_incidents_severity", "incidents", ["severity"], unique=False)
    op.create_index("ix_incidents_status", "incidents", ["status"], unique=False)
    op.create_table(
        "work_orders",
        sa.Column("work_order_id", sa.String(length=10), nullable=False),
        sa.Column("plant_id", sa.String(length=9), nullable=False),
        sa.Column("equipment_id", sa.String(length=9), nullable=False),
        sa.Column("work_order_name", sa.String(length=150), nullable=False),
        sa.Column("work_order_type", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="open", nullable=False
        ),
        sa.Column("linked_incident_id", sa.String(length=11), nullable=True),
        sa.Column("assigned_team", sa.String(length=100), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_labor_hours", sa.Float(), nullable=True),
        sa.Column("actual_labor_hours", sa.Float(), nullable=True),
        sa.Column("estimated_cost", sa.Float(), nullable=True),
        sa.Column("actual_cost", sa.Float(), nullable=True),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("completion_notes", sa.String(length=1000), nullable=True),
        sa.Column(
            "is_synthetic_ground_truth",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "inserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT (status = 'assigned' AND assigned_team IS NULL)",
            name=op.f("ck_work_orders_assigned_has_team"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'assigned' AND started_at IS NOT NULL)",
            name=op.f("ck_work_orders_assigned_has_no_started_at"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'cancelled' AND cancelled_at IS NULL)",
            name=op.f("ck_work_orders_cancelled_has_cancelled_at"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'cancelled' AND completed_at IS NOT NULL)",
            name=op.f("ck_work_orders_cancelled_has_no_completed_at"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'completed' AND cancelled_at IS NOT NULL)",
            name=op.f("ck_work_orders_completed_has_no_cancelled_at"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'completed' AND completed_at IS NULL)",
            name=op.f("ck_work_orders_completed_has_completed_at"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'completed' AND started_at IS NULL)",
            name=op.f("ck_work_orders_completed_has_started_at"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'in_progress' AND assigned_team IS NULL)",
            name=op.f("ck_work_orders_in_progress_has_team"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'in_progress' AND cancelled_at IS NOT NULL)",
            name=op.f("ck_work_orders_in_progress_has_no_cancelled_at"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'in_progress' AND completed_at IS NOT NULL)",
            name=op.f("ck_work_orders_in_progress_has_no_completed_at"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'in_progress' AND started_at IS NULL)",
            name=op.f("ck_work_orders_in_progress_has_started_at"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'open' AND cancelled_at IS NOT NULL)",
            name=op.f("ck_work_orders_open_has_no_cancelled_at"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'open' AND completed_at IS NOT NULL)",
            name=op.f("ck_work_orders_open_has_no_completed_at"),
        ),
        sa.CheckConstraint(
            "NOT (status = 'open' AND started_at IS NOT NULL)",
            name=op.f("ck_work_orders_open_has_no_started_at"),
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'medium', 'high', 'critical')",
            name=op.f("ck_work_orders_valid_priority"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'assigned', 'in_progress', 'completed', 'cancelled')",
            name=op.f("ck_work_orders_valid_status"),
        ),
        sa.CheckConstraint(
            "work_order_type IN ('corrective', 'preventive', 'predictive', 'inspection', 'emergency')",
            name=op.f("ck_work_orders_valid_work_order_type"),
        ),
        sa.CheckConstraint(
            "actual_cost IS NULL OR actual_cost >= 0",
            name=op.f("ck_work_orders_actual_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "actual_labor_hours IS NULL OR actual_labor_hours >= 0",
            name=op.f("ck_work_orders_actual_labor_non_negative"),
        ),
        sa.CheckConstraint(
            "cancelled_at IS NULL OR cancelled_at >= created_at",
            name=op.f("ck_work_orders_cancelled_not_before_created"),
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= created_at",
            name=op.f("ck_work_orders_completed_not_before_created"),
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at",
            name=op.f("ck_work_orders_completed_not_before_started"),
        ),
        sa.CheckConstraint(
            "estimated_cost IS NULL OR estimated_cost >= 0",
            name=op.f("ck_work_orders_estimated_cost_non_negative"),
        ),
        sa.CheckConstraint(
            "estimated_labor_hours IS NULL OR estimated_labor_hours >= 0",
            name=op.f("ck_work_orders_estimated_labor_non_negative"),
        ),
        sa.CheckConstraint(
            "scheduled_at IS NULL OR scheduled_at >= created_at",
            name=op.f("ck_work_orders_scheduled_not_before_created"),
        ),
        sa.CheckConstraint(
            "started_at IS NULL OR scheduled_at IS NULL OR started_at >= scheduled_at",
            name=op.f("ck_work_orders_started_not_before_scheduled"),
        ),
        sa.CheckConstraint(
            "started_at IS NULL OR started_at >= created_at",
            name=op.f("ck_work_orders_started_not_before_created"),
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.equipment_id"],
            name=op.f("fk_work_orders_equipment_id_equipment"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["linked_incident_id"],
            ["incidents.incident_id"],
            name=op.f("fk_work_orders_linked_incident_id_incidents"),
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.plant_id"],
            name=op.f("fk_work_orders_plant_id_plants"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("work_order_id", name=op.f("pk_work_orders")),
    )
    op.create_index(
        "ix_work_orders_created_at", "work_orders", ["created_at"], unique=False
    )
    op.create_index(
        "ix_work_orders_equipment_id", "work_orders", ["equipment_id"], unique=False
    )
    op.create_index(
        "ix_work_orders_linked_incident_id",
        "work_orders",
        ["linked_incident_id"],
        unique=False,
    )
    op.create_index(
        "ix_work_orders_plant_equipment_created_at",
        "work_orders",
        ["plant_id", "equipment_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_work_orders_plant_id", "work_orders", ["plant_id"], unique=False
    )
    op.create_index(
        "ix_work_orders_priority", "work_orders", ["priority"], unique=False
    )
    op.create_index(
        "ix_work_orders_scheduled_at", "work_orders", ["scheduled_at"], unique=False
    )
    op.create_index("ix_work_orders_status", "work_orders", ["status"], unique=False)
    op.create_index(
        "ix_work_orders_work_order_type",
        "work_orders",
        ["work_order_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_work_orders_work_order_type", table_name="work_orders")
    op.drop_index("ix_work_orders_status", table_name="work_orders")
    op.drop_index("ix_work_orders_scheduled_at", table_name="work_orders")
    op.drop_index("ix_work_orders_priority", table_name="work_orders")
    op.drop_index("ix_work_orders_plant_id", table_name="work_orders")
    op.drop_index("ix_work_orders_plant_equipment_created_at", table_name="work_orders")
    op.drop_index("ix_work_orders_linked_incident_id", table_name="work_orders")
    op.drop_index("ix_work_orders_equipment_id", table_name="work_orders")
    op.drop_index("ix_work_orders_created_at", table_name="work_orders")
    op.drop_table("work_orders")
    op.drop_index("ix_incidents_status", table_name="incidents")
    op.drop_index("ix_incidents_severity", table_name="incidents")
    op.drop_index("ix_incidents_plant_id", table_name="incidents")
    op.drop_index("ix_incidents_plant_equipment_occurred_at", table_name="incidents")
    op.drop_index("ix_incidents_occurred_at", table_name="incidents")
    op.drop_index("ix_incidents_linked_alarm_id", table_name="incidents")
    op.drop_index("ix_incidents_equipment_id", table_name="incidents")
    op.drop_index("ix_incidents_category", table_name="incidents")
    op.drop_table("incidents")
    op.drop_index("ix_scada_observations_timestamp", table_name="scada_observations")
    op.drop_index(
        "ix_scada_observations_state_timestamp", table_name="scada_observations"
    )
    op.drop_index(
        "ix_scada_observations_quality_timestamp", table_name="scada_observations"
    )
    op.drop_index(
        "ix_scada_observations_plant_timestamp", table_name="scada_observations"
    )
    op.drop_index("ix_scada_observations_plant_id", table_name="scada_observations")
    op.drop_index(
        "ix_scada_observations_equipment_timestamp", table_name="scada_observations"
    )
    op.drop_table("scada_observations")
    op.drop_index("ix_ground_truth_events_started_at", table_name="ground_truth_events")
    op.drop_index("ix_ground_truth_events_severity", table_name="ground_truth_events")
    op.drop_index(
        "ix_ground_truth_events_plant_started_at", table_name="ground_truth_events"
    )
    op.drop_index(
        "ix_ground_truth_events_plant_severity", table_name="ground_truth_events"
    )
    op.drop_index("ix_ground_truth_events_plant_id", table_name="ground_truth_events")
    op.drop_index("ix_ground_truth_events_event_type", table_name="ground_truth_events")
    op.drop_index(
        "ix_ground_truth_events_equipment_started_at", table_name="ground_truth_events"
    )
    op.drop_index(
        "ix_ground_truth_events_equipment_id", table_name="ground_truth_events"
    )
    op.drop_index("ix_ground_truth_events_ended_at", table_name="ground_truth_events")
    op.drop_table("ground_truth_events")
    op.drop_index("ix_alarms_status", table_name="alarms")
    op.drop_index("ix_alarms_severity", table_name="alarms")
    op.drop_index("ix_alarms_raised_at", table_name="alarms")
    op.drop_index("ix_alarms_plant_id", table_name="alarms")
    op.drop_index("ix_alarms_plant_equipment_raised_at", table_name="alarms")
    op.drop_index("ix_alarms_equipment_id", table_name="alarms")
    op.drop_index("ix_alarms_category", table_name="alarms")
    op.drop_index("ix_alarms_alarm_code", table_name="alarms")
    op.drop_table("alarms")
    op.drop_index(
        "ix_weather_observations_timestamp", table_name="weather_observations"
    )
    op.drop_index(
        "ix_weather_observations_station_timestamp", table_name="weather_observations"
    )
    op.drop_index(
        "ix_weather_observations_quality_timestamp", table_name="weather_observations"
    )
    op.drop_index(
        "ix_weather_observations_plant_timestamp", table_name="weather_observations"
    )
    op.drop_index("ix_weather_observations_plant_id", table_name="weather_observations")
    op.drop_table("weather_observations")
    op.drop_index("ix_tariffs_tariff_type", table_name="tariffs")
    op.drop_index("ix_tariffs_status", table_name="tariffs")
    op.drop_index("ix_tariffs_plant_status", table_name="tariffs")
    op.drop_index("ix_tariffs_plant_id", table_name="tariffs")
    op.drop_index("ix_tariffs_plant_effective_from", table_name="tariffs")
    op.drop_index("ix_tariffs_effective_to", table_name="tariffs")
    op.drop_index("ix_tariffs_effective_from", table_name="tariffs")
    op.drop_table("tariffs")
    op.drop_index("ix_equipment_status", table_name="equipment")
    op.drop_index("ix_equipment_plant_id", table_name="equipment")
    op.drop_index("ix_equipment_parent_equipment_id", table_name="equipment")
    op.drop_index("ix_equipment_equipment_type", table_name="equipment")
    op.drop_index("ix_equipment_commissioning_date", table_name="equipment")
    op.drop_table("equipment")
    op.drop_index("ix_budgets_status", table_name="budgets")
    op.drop_index("ix_budgets_plant_id", table_name="budgets")
    op.drop_index("ix_budgets_plant_fiscal_year", table_name="budgets")
    op.drop_index("ix_budgets_fiscal_year", table_name="budgets")
    op.drop_index("ix_budgets_category", table_name="budgets")
    op.drop_index("ix_budgets_approved_on", table_name="budgets")
    op.drop_table("budgets")
    op.drop_index("ix_plants_status", table_name="plants")
    op.drop_index("ix_plants_region", table_name="plants")
    op.drop_index("ix_plants_commissioning_date", table_name="plants")
    op.drop_table("plants")
    # ### end Alembic commands ###
